name: diversitree_mobile
description: "Diversitree project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  sqflite: 2.3.0
  google_fonts: 6.2.1
  permission_handler: 10.0.0
  image: 4.5.2
  http: 1.3.0
  flutter:
    sdk: flutter
  intl: 0.20.1
  geolocator: 13.0.2
  camera: 0.11.1
  path: 1.9.0
  flutter_launcher_icons: ^0.14.3
  qr_code_scanner_plus: ^2.0.9+1
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - storage/